# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo 
    - name: Register into GitHub and clones master into copy-target
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git branch -D copy-target
        git branch -b copy-target
    - name: Create local changes     
      run: python3 ./sync-script/replace_links.py
    - name: Commit files
      run: |
        git add .
        git commit -m "Automatic switch of links to xrefs" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ 'copy-target' }}
