name: Replace links with uids in copy branch

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Run python script to replace the links     
      run: python3 ./sync-script/replace_links.py
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        $ThisCommit = "${{ github.sha }}"
        git checkout copy-target
        git reset --hard $ThisCommit
        python3 ./sync-script/replace_links.py
        git add .
        git commit -m "Automatic switch of links to xrefs" -a
      shell: pwsh
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: copy-target
